package app.admin.form;

import javax.swing.ImageIcon;

/**
 *
 * @author shahi
 */
public class AdminCarCategory extends javax.swing.JPanel {

    public AdminCarCategory(String category, String brand, String powerSource, String limitations, String price, String quantity, ImageIcon carImage) {
        initComponents();
        
        lbcarCategory1.setText(category); 
        lbcarMilage1.setText(limitations);
        lbcarPrice1.setText(price);
        lbcarSeats1.setText(quantity);
        lbcarName1.setText(brand);
        
        if (carImage != null) {
            pic1.setImage(carImage);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shadowPanel1 = new app.vehicle.design.ShadowPanel();
        pic1 = new app.vehicle.design.PictureBox();
        lbcarType1 = new javax.swing.JLabel();
        lbcarName1 = new javax.swing.JLabel();
        lbcarFeatures1 = new javax.swing.JLabel();
        pictureBox3 = new app.vehicle.design.PictureBox();
        lbcarSeats1 = new javax.swing.JLabel();
        pictureBox6 = new app.vehicle.design.PictureBox();
        lbcarMilage1 = new javax.swing.JLabel();
        lbcarCategory1 = new javax.swing.JLabel();
        pictureBox5 = new app.vehicle.design.PictureBox();
        lbreserveDetails1 = new javax.swing.JButton();
        lbcarPrice1 = new javax.swing.JLabel();

        pic1.setImage(new javax.swing.ImageIcon(getClass().getResource("/app/dashboard/png/Vector (5).png"))); // NOI18N

        lbcarType1.setText("Luxury");

        lbcarName1.setText("Pagani");

        lbcarFeatures1.setText("Features");

        pictureBox3.setImage(new javax.swing.ImageIcon(getClass().getResource("/app/vehicle/logo/UserIcon.png"))); // NOI18N

        lbcarSeats1.setText("5");

        pictureBox6.setFocusable(false);
        pictureBox6.setImage(new javax.swing.ImageIcon(getClass().getResource("/app/dashboard/png/Clip path group.png"))); // NOI18N

        lbcarMilage1.setText("Unlimited Milage");

        lbcarCategory1.setText("Electric");

        pictureBox5.setImage(new javax.swing.ImageIcon(getClass().getResource("/app/vehicle/logo/UserIcon.png"))); // NOI18N

        lbreserveDetails1.setBackground(new java.awt.Color(255, 102, 0));
        lbreserveDetails1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbreserveDetails1.setForeground(new java.awt.Color(255, 255, 255));
        lbreserveDetails1.setText("Reserve Deal");
        lbreserveDetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbreserveDetails1ActionPerformed(evt);
            }
        });

        lbcarPrice1.setText("NRs. 17,000");

        javax.swing.GroupLayout shadowPanel1Layout = new javax.swing.GroupLayout(shadowPanel1);
        shadowPanel1.setLayout(shadowPanel1Layout);
        shadowPanel1Layout.setHorizontalGroup(
            shadowPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shadowPanel1Layout.createSequentialGroup()
                .addComponent(pic1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(shadowPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(shadowPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(shadowPanel1Layout.createSequentialGroup()
                        .addComponent(lbcarPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(lbreserveDetails1)
                        .addGap(33, 33, 33))
                    .addGroup(shadowPanel1Layout.createSequentialGroup()
                        .addGroup(shadowPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbcarName1)
                            .addComponent(lbcarType1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbcarFeatures1)
                            .addGroup(shadowPanel1Layout.createSequentialGroup()
                                .addComponent(pictureBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbcarSeats1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(pictureBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbcarCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(shadowPanel1Layout.createSequentialGroup()
                                .addComponent(pictureBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbcarMilage1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        shadowPanel1Layout.setVerticalGroup(
            shadowPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shadowPanel1Layout.createSequentialGroup()
                .addComponent(pic1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbcarType1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbcarName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbcarFeatures1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(shadowPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(shadowPanel1Layout.createSequentialGroup()
                        .addGroup(shadowPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbcarSeats1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pictureBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbcarCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbcarMilage1))
                    .addGroup(shadowPanel1Layout.createSequentialGroup()
                        .addComponent(pictureBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pictureBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(shadowPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbreserveDetails1)
                    .addComponent(lbcarPrice1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(shadowPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shadowPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbreserveDetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbreserveDetails1ActionPerformed

    }//GEN-LAST:event_lbreserveDetails1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbcarCategory1;
    private javax.swing.JLabel lbcarFeatures1;
    private javax.swing.JLabel lbcarMilage1;
    private javax.swing.JLabel lbcarName1;
    private javax.swing.JLabel lbcarPrice1;
    private javax.swing.JLabel lbcarSeats1;
    private javax.swing.JLabel lbcarType1;
    private javax.swing.JButton lbreserveDetails1;
    private app.vehicle.design.PictureBox pic1;
    private app.vehicle.design.PictureBox pictureBox3;
    private app.vehicle.design.PictureBox pictureBox5;
    private app.vehicle.design.PictureBox pictureBox6;
    private app.vehicle.design.ShadowPanel shadowPanel1;
    // End of variables declaration//GEN-END:variables
}
